name: Workflow Information

on:
  workflow_dispatch:

jobs:
  print:
    runs-on: ubuntu-latest

    steps:
      - name: Trigger Information
        run: echo "The workflow is triggered by event: ${{ github.event_name }} . it is failling"

      - name: Jobs Information
        run: echo "The workflow contains at least one job"

      - name: Summary
        run: echo "This workflow has completed its steps."
