name: Hello GitHub Actions

on:
  workflow_dispatch:
  
jobs:
  print:
    runs-on: ubuntu-latest

    steps:
      - name: Trigger Information
        run: echo "The workflow is triggered by event: ${{ github.event_name }}"
  
   
      - name: jobs information
        run: echo "The workflow contain at least one job"
    
  
      - name: Summary
        run: echo "This workflow has completed its steps."
