
name: Push Workflow

on:
  #push:
  workflow_dispatch:
    

jobs:
  pushjob:
    runs-on: ubuntu-latest

    steps:
      - name: "push trigger"
        run: |
          echo "Push workflow triggered ${{github.event_name}}"

      - name: "show branch"
        run: |
          echo "Branch: ${{github.ref}}"
      - name: "show commit"
        run: |
          echo "Commit: ${{github.sha}}"